title: Tom Hume
description: Snagged on frowns, and slowly dawns

url: http://twhume.github.io/
baseurl: ""
paginate_path: "/page:num/"
permalink: /:title/

markdown: kramdown
theme: slate
highlighter: rouge
gems: [jekyll-paginate]
paginate: 15

navigation:
 - title: home
   url: /index.html
 - title: linkedin
   url: https://www.linkedin.com/in/twhume 
 - title: github 
   url: https://github.com/twhume

social:
   github: twhume 
   twitter: twhume 
   email: twhume@gmail.com

google_analytics: "UA-940399-1"
